// Sizing
const softmax=(arr,t=20)=>{ const ex=arr.map(x=>Math.exp(x/t)); const s=ex.reduce((a,b)=>a+b,0)||1; return ex.map(x=>x/s); };
const wExp=softmax(selected.map(x=>x.exp_lcb_bps),20);
const TARGET_PORT_RISK_BPS=52;

// Build picks with flipped side (buy<->sell), keep TP/SL/RRR and all other fields unchanged
const picks = selected.map((x,i)=>({
  symbol: x.base,
  symbol_full: x.symbol,
  quote: x.quote,

  // Flip side here
  side: x.side === "long" ? "short" : "long",

  score: x.score, rank:i+1,
  ttl_sec: clamp(Math.round(x.hold_sec + i*12), 480, 2000),
  p_win:x.p_win, p_lcb:x.p_lcb,
  exp_bps:x.exp_bps, exp_lcb_bps:x.exp_lcb_bps,
  tp_bps:x.tp_bps, sl_bps:x.sl_bps, rrr:x.rrr,
  tp_atr_mult:x.tp_atr, sl_atr_mult:x.sl_atr,
  spread_bps:x.spread_bps, cost_bps:x.cost_bps,
  adx:x.adx, atr_bps:x.atr_bps, beta_r2:x.beta_r2, n_conf:x.n_conf, obi:x.obi, confl:x.confl,
  regime:x.regime, style:x.style,
  liq_pct:x.liq_pct, fill_prob:x.fill_prob,
  size_bps: x.sl_bps>0 ? Math.min(220, Math.round(wExp[i]*TARGET_PORT_RISK_BPS/x.sl_bps*100)) : 0
}));
