name: Send Trade Ideas (auto base, auto-RRR, 3h cooldown)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ideas-push
  cancel-in-progress: true

jobs:
  push-ideas:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Health check (Worker)
        env:
          WORKER_PUSH_URL: ${{ secrets.WORKER_PUSH_URL }}
        run: |
          node - <<'NODE'
          (async ()=>{
            try{
              const base = process.env.WORKER_PUSH_URL;
              if(!base){ console.log("[gha] health: WORKER_PUSH_URL missing"); process.exit(1); }
              const u = new URL(base); u.pathname="/health"; u.search="";
              const r = await fetch(u.toString());
              const t = await r.text().catch(()=> "");
              console.log("[gha] health", r.status, t);
            }catch(e){
              console.log("[gha] health failed:", e?.message || e);
            }
          })();
          NODE

      - name: Show config (sanitized)
        env:
          WORKER_PUSH_URL: ${{ secrets.WORKER_PUSH_URL }}
          PUSH_TOKEN_SET: ${{ secrets.PUSH_TOKEN != '' }}
          TOP_N: ${{ vars.TOP_N }}
          MIN_24H_QV: ${{ vars.MIN_24H_QV }}
          TTL_SEC: ${{ vars.TTL_SEC }}
        run: |
          echo "[gha] WORKER_PUSH_URL host:" $(node -e "try{const u=new URL(process.env.WORKER_PUSH_URL);console.log(u.host)}catch{console.log('(missing)')}")
          echo "[gha] PUSH_TOKEN set:" "${PUSH_TOKEN_SET}"
          echo "[gha] TOP_N:" "${TOP_N}"
          echo "[gha] MIN_24H_QV:" "${MIN_24H_QV}"
          echo "[gha] TTL_SEC:" "${TTL_SEC}"

      - name: Push Ideas (ideas-pusher.js)
        env:
          WORKER_PUSH_URL: ${{ secrets.WORKER_PUSH_URL }}
          PUSH_TOKEN:      ${{ secrets.PUSH_TOKEN }}
          # These are read by your ideas-pusher.js
          TOP_N:           ${{ vars.TOP_N }}          # optional (default 10)
          MIN_24H_QV:      ${{ vars.MIN_24H_QV }}     # optional (default 10000000)
          TTL_SEC:         ${{ vars.TTL_SEC }}        # optional (default 900)
        run: |
          echo "[gha] running ideas-pusher.js"
          node .github/workflows/ideas-pusher.js
