name: Ideas Pusher
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}
concurrency:
  group: ideas-pusher
  cancel-in-progress: false
jobs:
  push-ideas:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Push ideas
        env:
          WORKER_PUSH_URL: ${{ secrets.WORKER_PUSH_URL }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          TOP_N: "10"
          MIN_24H_QV: "10000000"
          TTL_SEC: "900"
        run: node ideas-pusher.js
